spring:
    application:
        name: XTR

application:
    dslPath: DSL

    ssl:
        certification:
        key:
        keystore-password: defaultpassword

    client-data:
        member-class: GOV
        member-code: 70006317
        subsystem-code: byrokratt
        default-userId: EE11111111111

    security-server: https://out.test.x-tee.ee:443/
    xroad-instance: ee-test